version: "3"
services:

#  redis:
#    container_name: redis1
#    image: redis:latest
#    command: redis-server --requirepass qlalfqjsgh
#    networks:
#      - backend

#  rabbit:
#    image: woozy9/rabbitwithplugin:latest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - backend

  app:
    image: woozy9/app:latest
    ports:
      - "8080:8080"
#    depends_on:
#      - redis
#      - rabbit
    networks:
      - backend

#networks:
#  backend: