spring:
  profiles:
    include:
      - secret

  batch:
    jdbc:
      initialize-schema: always


#  output:
#    ansi:
#      enabled: always

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  #  datasource:
  #    url: jdbc:h2:mem:db

  jpa:

    open-in-view: off

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update

    defer-datasource-initialization: true

#  datasource:
#    url: ${{ secrets.SPRING_DATASOURCE_URL }}
#    username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
#    password: ${{ secrets.SPRING_PASSWORD }}
#
#  rabbitmq:
#    host: ${{ secrets.SPRING_RABBIT_HOST }}
#    port: 5672
#    username: ${{ secrets.SPRING_RABBIT_USERNAME }}
#    password: ${{ secrets.SPRING_PASSWORD }}
#
#  data:
#    redis:
#      host: ${{ secrets.SPRING_REDIS_HOST }}
#      port: 6379
#      password: ${{ secrets.SPRING_PASSWORD }}
#
#auth:
#  jwt:
#    secret:
#      key: ${{ secrets.JWT }}
#    exp:
#      access: 1
#      refresh: 12

#logging:
#  level:
#    org:
#      springframework:
#        security: trace


