INSERT INTO PLAYER
    (PLAYER_EMAIL, PLAYER_PASSWORD, PLAYER_NAME, PLAYER_ROLE, PLAYER_LEVEL, PLAYER_AD, PLAYER_AS, PLAYER_HP, PLAYER_MAX_STAGE, PLAYER_CUR_STAGE, PLAYER_EXP, PLAYER_GOLD)
VALUES
    ('user@example.com', 'password', '테스터', 'REGULAR', 1, 5, 5.0, 50, 1, 1, 0, 0);

INSERT INTO MONSTER
    (MONSTER_TYPE, MONSTER_STAGE, MONSTER_NAME, MONSTER_LEVEL, MONSTER_AD, MONSTER_HP, MONSTER_DROP_EXP, MONSTER_DROP_GOLD)
VALUES
    ('NORMAL', 1, 'Firedrake', 1, 10, 10, 200, 50);

INSERT INTO ITEM
    (ITEM_NAME, ITEM_ATTR_NAME, ITEM_ATTR_VALUE, ITEM_TYPE, ITEM_CATEGORY)
VALUES
    ('목검', '공격력', 10, '장비', '무기');

INSERT INTO DROP_TABLE
    (MONSTER_ID, ITEM_ID, DROP_RATE)
values (1, 1, 0.5);