name: ci-cd

on:
  pull_request:
    types: [ closed ]
    branches: [ "develop" ]

jobs:
  buid:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPO }}

#      - name: Copy compose file to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          source: "./docker-compose.yml"
#          target: "/home/ubuntu/docker1"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            sudo docker stop app
            sudo docker rm app
            sudo docker rmi ${{ secrets.DOCKER_HUB_REPO }}
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_REPO }}:latest --name app

#            sudo docker-compose -f /home/ubuntu/docker1/docker-compose.yml down
#            sudo docker-compose -f /home/ubuntu/docker1/docker-compose.yml up -d